name: procgen_submission_003
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - blas=1.0
  - bleach=3.1.4
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cudatoolkit=10.2.89
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_metadata=1.6.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - ninja=1.9.0
  - notebook=6.0.3
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.0.2u
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pillow=7.1.2
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - pygments=2.6.1
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.0
  - python-dateutil=2.8.1
  - pytorch=1.5.0
  - pyzmq=18.1.1
  - qt=5.9.6
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.6.2
    - astor==0.8.1
    - astunparse==1.6.3
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - backcall==0.2.0
    - beautifulsoup4==4.9.1
    - cachetools==4.1.0
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.2.2
    - colorama==0.4.3
    - cycler==0.10.0
    - dm-tree==0.1.5
    - filelock==3.0.12
    - future==0.18.2
    - gast==0.2.2
    - glcontext==2.2.0
    - glfw==1.11.2
    - google==2.0.3
    - google-auth==1.17.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.29.0
    - gym==0.15.7
    - gym3==0.3.1
    - h5py==2.10.0
    - idna==2.9
    - imageio==2.8.0
    - imageio-ffmpeg==0.3.0
    - importlib-metadata==1.6.1
    - ipdb==0.13.2
    - ipython==7.15.0
    - ipython-genutils==0.2.0
    - joblib==0.15.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - lz4==3.1.0
    - markdown==3.2.2
    - matplotlib==3.2.1
    - moderngl==5.6.1
    - msgpack==0.6.2
    - multidict==4.7.6
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - opencv-python-headless==4.2.0.34
    - opt-einsum==3.2.1
    - pandas==1.0.4
    - pickleshare==0.7.5
    - procgen==0.10.2
    - protobuf==3.12.2
    - ptyprocess==0.6.0
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyglet==1.5.0
    - pyparsing==2.4.7
    - pytz==2020.1
    - pyyaml==5.3.1
    - ray==0.8.5
    - redis==3.4.1
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - soupsieve==2.0.1
    - stable-baselines==2.10.0
    - tabulate==0.8.7
    - tensorboard==2.1.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==2.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - torch==1.5.0
    - torchvision==0.6.0
    - tqdm==4.46.1
    - urllib3==1.25.9
    - wcwidth==0.2.4
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - yarl==1.4.2
prefix: /home/wulfebw/programming/install/miniconda3/envs/procgen

